services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-server
    hostname: rmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
